### ISSUE TITLE
CSS Validator does not support CSS3 Variables

### ISSUE THREAD

**Issue by 0blu** [marianpg/fhw-web#3]
Hello,

it seems that the _CSS validator_ does not support any kind of [CSS3 Variables](https://caniuse.com/#feat=css-variables).

The css that I used to create the error:
```css
:root {
    --color-blue: #0000FF;
}

h1 {
    color: var(--color-blue);
}
```

The resulting error:
```
Error: Parse Error (in line 2)
Parse Error (in line 3)
Value Error :  color (nullcolors.html#propdef-color)

                                Parse Error (in line 6)
```

The current fix would be to just disable the _validator_ inside the server options:
```
[...]
    validator: {
        css: false,
    }
[...]
```

Edit: It's probably an error from the w3c css-validator (https://github.com/w3c/css-validator/issues/111)
